name: "Test NixOS flake"

on:
  pull_request:
  schedule:
    - cron: "0 13 * * 1"

jobs:
  pre-commit:
    name: Checks linting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    - uses: pre-commit/action@v3.0.0

  nix-run:
    name: Run NixOS Flake and upload generated PDFs
    needs: pre-commit
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4

    - name: Set up NixOS
      uses: cachix/install-nix-action@7ac1ec25491415c381d9b62f0657c7a028df52a7 # v24
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Run nix build
      run: nix build

    - name: Show logs on failure
      if: failure()
      run: nix log /nix/store/*dnd-char-sheet*.drv

    - name: Run nix flake check
      run: nix flake check

    - name: Copy output to archive directory
      run: |
       mkdir archive
       cp -r ./result/* ./archive

    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: result
        path: archive
